//This is code to solve problem 2 on Project Euler
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
*/
#include <iostream>;
using namespace std;

int main () {
    int back2=0;
    int back1=1;
    int sequence=0;
    int sum=0;
    do {
        sequence=back1+back2;
        back2=back1;
        back1=sequence;
        if (sequence%2==0){
            sum+=sequence;
        }
    } while(sequence<=4000000);
    cout << "The answer is " << sum <<"\n";
    return 0;

}
/*
 *more elegant solution involving phi and properties of Fibonacci sequence
*/
